[build.environment]
  VITE_BACKEND_URL = "https://nextmarketpoints.netlify.app/api"

[[redirects]]
  from = "/api/news/*"
  to = "https://nextmarketpoints.netlify.app/api/news/:splat"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }

[[redirects]]
  from = "/api/strategies/*"
  to = "https://nextmarketpoints.netlify.app/api/strategies/:splat"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }

[[redirects]]
  from = "/api/*"
  to = "https://nextmarketpoints.netlify.app/api/:splat"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }
